#!/bin/csh -f
# RCSid: $Id$
# Make source tags files for vi
cd common
echo "Making tags file in common..."
ctags -w *.[ch]
cd ..
foreach d (cv gen hd ot px rt util)
cd $d
echo "Making tags file in $d..."
ctags -w `find *.[ch] -type f -print` ../common/*.[ch]
cd ..
end
