.\" RCSid $Id$"
.TH DCTIMESTEP 1 12/09/09 RADIANCE
.SH NAME
dctimestep - compute annual simulation time-step via matrix multiplication
.SH SYNOPSIS
.B dctimestep
.B DCspec
[
.B skyvec
]
.br
.B dctimestep
.B Vspec
.B Tbsdf.xml
.B Dmat.dat
[
.B skyvec
]
.SH DESCRIPTION
.I Dctimestep
has two invocation forms.
In the first form,
.I dctimestep
is given a daylight coefficient specification and an optional sky
vector, which may be read from the standard input if unspecified.
The daylight coefficients are multiplied against this vector and the results
are written to the standard output.
This may be a list of color values or a combined Radiance image,
as explained below.
.PP
In the second form,
.I dctimestep
takes four input files, forming a matrix expression.
The first argument is the View matrix file that specifies how window output
directions are related to some set of measured values, such as an array of
illuminance points or images.
This matrix is usually computed by
.I rtcontrib(1)
for a particular set of windows or skylight openings.
The second argument is the window transmission matrix, or BSDF, given as
a standard XML description.
The third argument is the Daylight matrix file that defines how sky patches
relate to input directions on the same opening.
This is usually computed using
.I genklemsamp(1)
with
.I rtcontrib
in a separate run for each window or skylight orientation.
The final input is the sky contribution vector,
usually computed by
.I genskyvec(1),
which may be passed on the standard input.
This data must be in ASCII format, whereas the View and Daylight matrices
are more efficiently represented as binary float data if machine
byte-order is not an issue.
.PP
Sent to the standard output of
.I dctimestep
is either an ASCII color vector with as many RGB triplets
as there are rows in the View matrix, or a combined
.I Radiance
picture.
Which output is produced depends on the first argument.
A regular file name will be loaded and interpreted as a matrix to
generate a color results vector.
A file specification containing a '%d' format string will be
interpreted as a list of
.I Radiance
component pictures, which will be summed according to the computed
vector.
.SH EXAMPLES
To compute workplane illuminances at 3:30pm on Feb 10th:
.IP "" .2i
gensky 2 10 15:30 | genskyvec | dctimestep workplaneDC.dmx > Ill_02-10-1530.dat
.PP
To compute an image at 10am on the equinox from a set of component images:
.IP "" .2i
gensky 3 21 10 | genskyvec | dctimestep viewc%03d.hdr > view_03-21-10.hdr
.PP
To compute a set of illuminance contributions for Window 1 on
the Winter solstice at 2pm:
.IP "" .2i
gensky 12 21 14 | genskyvec | dctimestep IllPts.vmx Blinds20.xml Window1.dmx > Ill_12-21-14.dat
.PP
To compute Window2's contribution to an interior view at 12 noon on the Summer solstice:
.IP "" .2i
gensky 6 21 12 | genskyvec | dctimestep view%03d.hdr Blinds30.xml Window2.dmx > view_6-21-12.hdr
.SH AUTHOR
Greg Ward
.SH "SEE ALSO"
genklemsamp(1), genskyvec(1), mkillum(1), rtcontrib(1), rtrace(1), vwrays(1)
