.\" RCSid $Id$
.TH EPW2WEA 08/07/13 RADIANCE
.SH NAME
epw2wea - weather file converter
.SH SYNOPSIS
.B epw2wea
.B file_name.epw
.B file_name.wea
.SH DESCRIPTION
.I epw2wea 
transforms an EnergyPlus weather data (.epw) file into the DAYSIM weather file
format, for use with the RADIANCE gendaymtx program.
.SH AUTHOR
Christoph Reinhart, Jason Turner
.SH "SEE ALSO"
gendaymtx(1)
