.\" RCSid "$Id$"
.TH "FALSECOLOR" "1" "12/12/11" "RADIANCE" ""
.SH "NAME"
falsecolor \- make a false color RADIANCE picture
.SH "SYNOPSIS"
.B falsecolor
[
.B "\-i input"
][
.B "\-p picture"
][
.B "\-cb | \-cl | \-cp"
][
.B \-e
][
.B "\-s scale"
][
.B "\-l label"
][
.B "\-n ndivs"
][
.B "\-lw lwidth"
][
.B "\-lh lheight"
][
.B "\-log decades"
][
.B "\-m mult"
][
.B "\-pal palette"
][
.B "\-r redv"
][
.B "\-g grnv"
][
.B "\-b bluv"
]

.B falsecolor \-palettes
.SH "DESCRIPTION"
.I Falsecolor
produces a false color picture for lighting analysis.
Input is a rendered Radiance picture.
.PP 
By default, luminance is displayed on a linear scale from 0 to 1000 cd/m2, where
dark areas are purple and brighter areas move through blue, green, red to yellow.
A different scale can be given with the
.I \-s
option.
If the argument given to
.I \-s
begins with an "a" for "auto," then the maximum is used for scaling the result.
The default multiplier is 179, which converts from radiance or irradiance
to luminance or illuminance, respectively.
A different multiplier can be given with
.I \-m
to get daylight factors or whatever.
For a logarithmic rather than a linear mapping, the
.I \-log
option can be used, where
.I decades
is the number of decades below the maximum scale desired.
.PP 
A legend is produced for the new image with a label given by the
.I \-l
option.
The default label is "cd/m2", which is appropriate for standard Radiance
images.
If the
.I \-i
option of
.I rpict(1)
was used to produce the image, then the appropriate label would be "Lux".
.PP 
If contour lines are desired rather than just false color, the
.I \-cl
option can be used.
These lines can be placed over another Radiance picture using the
.I \-p
option.
If the input picture is given with
.I \-ip
instead of
.I \-i,
then it will be used both as the source of values and as the picture
to overlay with contours.
The
.I \-cb
option produces contour bands instead of lines, where the thickness of
the bands is related to the rate of change in the image.
The
.I \-cp
option creates a posterization effect where colours are banded without
the background image showing through.
The
.I \-n
option can be used to change the number of contours (and corresponding
legend entries) from the default value of 8.
The
.I \-lw
and
.I \-lh
options may be used to change the legend dimensions from the default width
and height of 100x200.
A value of zero in either eliminates the legend in the output.
.PP 
The
.I \-e
option causes extrema points to be printed on the brightest and
darkest pixels of the input picture.
.PP 
The
.I "\-pal"
option provides different color palettes for
.I falsecolor.
The current choices are
.I spec
for the old spectral mapping,
.I hot
for a thermal scale,
.I eco
for a blue-red-yellow scale, and
.I pm3d
for a variation of the default mapping,
.I def.
A Radiance HDR image of all available palettes can be created with the 
.I \-palettes
option.
The remaining options,
.I "\-r, \-g,"
and
.I \-b
are for changing the mapping of values to colors.
These are expressions of the variable 
.I v,
where
.I v
varies from 0 to 1.
These options are not recommended for the casual user.
.PP 
If no
.I \-i
or
.I \-ip
option is used, input is taken from the standard input.
The output image is always written to standard output, which should
be redirected.
.SH "EXAMPLES"
To create a false color image directly from
.I rpict(1):
.IP "" .2i
rpict \-vf default.vp scene.oct | falsecolor > scene.hdr
.PP
To show the available color palettes:
.IP "" .2i
falsecolor -palettes | ximage
.PP 
To create a logarithmic contour plot of illuminance values on a
Radiance image:
.IP "" .2i
rpict \-i \-vf default.vp scene.oct > irrad.hdr
.br 
rpict \-vf default.vp scene.oct > rad.hdr
.br 
falsecolor \-i irrad.hdr \-p rad.hdr \-cl \-log 2 \-l Lux > lux.hdr
.SH "AUTHOR"
Greg Ward
.br 
Axel Jacobs (Perl translation and \-pal options)
.SH "ACKNOWLEDGEMENT"
Work on this program was initiated and sponsored by the LESO
group at EPFL in Switzerland. The 'eco' palette was sponsored by Foster + Partners in London.
.SH "SEE ALSO"
getinfo(1), pcomb(1), pcompos(1), pextrem(1), pfilt(1), pflip(1), protate(1),
psign(1), rpict(1), ximage(1)
