.\" RCSid "$Id$"
.TH IGRAPH 1 6/24/98 RADIANCE
.SH NAME
igraph - interactive graphing program
.SH DESCRIPTION
.I Igraph
is a crude interactive program for creating line and scatter
plots.
Provisions for reading and writing graph files as well
as changing variables and getting output are provided from
a menu.
.PP
Graph files and variables are as described in bgraph(1).
.SH AUTHOR
Greg Ward
.SH BUGS
There is no mechanism provided for undefining a variable.
.SH "SEE ALSO"
bgraph(1), icalc(1), metafile(5)
