.\" 
.TH "LTVIEW" "1" "08/04/14" "RADIANCE" ""
.SH "NAME"
ltview \- view photometry of a light source
.SH "SYNOPSIS"
.B ltview
[
.B \-i
][
.B "\-b boxsize"
][
.B "\-o device"
]
input
.SH "DESCRIPTION"
.I ltview
renders a Radiance luminiare or IES photometry interactively using
.I rad(1).
.PP 
.I ltview
accepts exactly one Radiance object or IES photometry
file as input.  No input is taken from STDIN.  The
.I \-i
option tells it that the input file contains 
IES photometry rather then a Radiance description of a 
luminiare.  In this case, Radiance's
.I ies2rad(1)
is called with its default settings to convert the IES file into a 
Radiance object.
.PP 
Unlike
.I objpict(1)
or
.I objview(1),
no additional light sources are added to the scene, since it is
assumed that the object is a luminaire.
.PP 
.I ltview
relies on Radiance's
.I rad(1)
command to compile an octree using 
.I oconv(1)
and to call
.I rvu(1)
to display an interactive preview of the luminaire.
The luminaire, or output from 
.I ies2rad(1),
is moved so that its center is at world origin.
.I ltview
then generates an open box around the fitting that is ten times
as big as the largest axis\-aligned dimension of the fitting.
The \-y face of the box is left open so that 
the camera can look inside, facing +y.
The overall dimensions of the enclosing box may be overwritten with the
.I "\-b boxsize"
option.  Note that both the fitting and the box are always centred at the
origin.
.PP 
When
.I ltview
is run with the
.I \-i
option, i.e. the file is an IES photometry file,
then the dimensions of the luminaire and intesity of its 
output are determined by
.I ies2rad(1)'s
default settings.  If this is not acceptable, then it is best to run
.I ies2rad(1)
manually, and to feed
.I ltview
the hand\-crafted fitting, rather than the IES photometry.  In any case,
it is likely that the initial exposure within the 
.I rvu(1)
window window needs to be adjusted before the distribution of the fitting
can be fully appreciated.
.PP 
The default
.I rvu(1)
output device is
.I x11
on all platforms except for Windows, where it is set to
.I qt.
This may be overwritten with the
.I "\-o output"
option.

.SH "EXAMPLES"
To query available output devices
.IP "" .2i
rvu \-devices
.PP 
To visualise an IES file with the qt driver
.IP "" .2i
ltview \-o qt ABC123.ies
.PP 
To look at a typical fluorescent fitting that is modelled in millimeters
.IP "" .2i
ltview \-b 5000 XYZ_batten.rad
.SH "AUTHOR"
Axel Jacobs
.SH "SEE ALSO"
ltpict(1), ies2rad(1), oconv(1), rad(1), rvu(1)
