.\" RCSid "$Id: ra_pr24.1,v 1.3 2004/03/26 22:58:20 greg Exp $"
.TH RA_PR24 1 11/15/93 RADIANCE
.SH NAME
ra_pr24 - convert RADIANCE picture to/from 24-bit rasterfile
.SH SYNOPSIS
.B ra_pr24
[
.B \-r
|
.B \-rgb
][
.B "\-g gamma"
][
.B "\-e +/-stops"
]
[
.B input
[
.B output
]
]
.SH DESCRIPTION
.I Ra_pr24
converts between RADIANCE and 24-bit pixrect rasterfile formats.
The
.I \-g
option specifies the exponent used in gamma correction;
the default value is 2.2.
An exponent of 1 turns gamma correction off.
The
.I \-e
option specifies an exposure compensation in f-stops (powers of two).
Only integer stops are allowed, for efficiency.
The
.I \-r
option invokes a reverse conversion, from a 24-bit rasterfile to
a RADIANCE picture.
If the
.I \-rgb
option is used, the output rasterfile will be in RGB byte-ordering
rather than the more standard (for Sun) BGR ordering.
Byte ordering is determined automatically for the reverse
conversion.
If the output file is missing, the standard output is used.
If the input file is missing as well, the standard input is used.
.SH AUTHOR
Greg Ward
.SH BUGS
Only standard 24-bit color rasterfiles are read or written.
.SH "SEE ALSO"
pfilt(1), ra_bmp(1), ra_bn(1), ra_ppm(1), ra_pr(1), ra_t8(1), ra_t16(1),
ra_tiff(1), ximage(1)
