.\" RCSid "$Id: rtcontrib.1,v 1.9 2005/06/10 16:42:10 greg Exp $"
.TH RTCONTRIB 1 5/25/05 RADIANCE
.SH NAME
rtcontrib - compute contribution coefficients in a RADIANCE scene
.SH SYNOPSIS
.B rtcontrib
[
.B "\-n nprocs"
][
.B \-r
][
.B "\-e expr"
][
.B "\-f source"
][
.B "\-o ospec"
][
.B "\-b binv"
]
{
.B "\-m mod | \-M file"
}
..
[
.B $EVAR
]
[
.B @file
]
[
rtrace options
]
.B octree
.br
.B "rtcontrib [ options ] \-defaults"
.SH DESCRIPTION
.I Rtcontrib
computes ray contributions (i.e., color coefficients)
for objects whose modifiers are named in one or more
.I \-m
settings.
These modifiers are usually materials associated with
light sources or sky domes, and must directly modify some geometric
primitives to be considered in the output.
A modifier list may also be read from a file using the
.I \-M
option.
.PP
The output of
.I rtcontrib
has many potential uses.
Source contributions can be used as components in linear combination to
reproduce any desired variation, e.g., simulating lighting controls or
changing sky conditions via daylight coefficients.
More generally,
.I rtcontrib
can be used to compute arbitrary input-output relationships in optical
systems, such as luminaires, light pipes, and shading devices.
.PP
.I Rtcontrib
calls
.I rtrace(1)
with the -oTW option to calculate the daughter ray
contributions for each input ray, and the output tallies
are sent to one or more destinations according to the given
.I \-o
specification.
If a destination begins with an exclamation mark ('!'), then
a pipe is opened to a command and data is sent to its standard input.
Otherwise, the destination is treated as a file.
An existing file of the same name is clobbered, unless the
.I \-r
option is specified, in which case data recovery is attempted.
If an output specification contains a "%s" format, this will be
replaced by the modifier name.
The
.I \-b
option may be used to further define
a "bin number" within each object if finer resolution is needed, and
this will be applied to a "%d" format in the output file
specification if present.
The actual bin number is computed at run time based on ray direction
and surface intersection, as described below.
The most recent
.I \-b
and
.I \-o
options to the left of each
.I \-m
setting affect only that modifier.
(The ordering of other options is unimportant.)\0
.PP
If a
.I \-b
expression is defined for a particular modifier,
the bin number will be evaluated at run time for each
ray contribution from
.I rtrace.
Specifically, each ray's world intersection point will be assigned to
the variables Px, Py, and Pz, and the normalized ray direction
will be assigned to Dx, Dy, and Dz.
These parameters may be combined with definitions given in
.I \-e
arguments and files read using the
.I \-f
option.
The computed bin value will be
rounded to the nearest whole number.
This mechanism allows the user to define precise regions or directions
they wish to accumulate, such as the Tregenza sky discretization,
which would be otherwise impossible to specify
as a set of RADIANCE primitives.
The rules and predefined functions available for these expressions are
described in the
.I rcalc(1)
man page.
Unlike
.I rcalc,
.I rtcontrib
will search the RADIANCE library directories for each file given in a
.I \-f
option.
(No search takes place if a file name begins with a '.', '/' or '~'
character.)\0
.PP
If no
.I \-o
specification is given, results are written on the standard output in order
of modifier (as given on the command line) then bin number.
Concatenated data is also sent to a single destination (i.e., an initial
.I \-o
specification without formatting strings).
If a "%s" format appears but no "%d" in the
.I \-o
specification, then each modifier will have its own output file, with
multiple values per record in the case of a non-zero
.I \-b
definition.
If a "%d" format appears but no "%s", then each bin will get its own
output file, with modifiers output in order in each record.
For text output, each RGB coefficient triple is separated by a tab,
with a newline at the end of each ray record.
For binary output formats, there is no such delimiter to mark
the end of each record.
.PP
Input and output format defaults to plain text, where each ray's
origin and direction (6 real values) are given on input,
and one line is produced per output file per ray.
Alternative data representations may be specified by the
.I \-f[io]
option, which is described in the
.I rtrace
man page along with the associated
.I \-x
and
.I \-y
resolution settings.
In particular, the color ('c') output data representation
together with positive dimensions for
.I \-x
and
.I \-y
will produce an uncompressed RADIANCE picture,
suitable for manipulation with
.I pcomb(1)
and related tools.
.PP
If the
.I \-n
option is specified with a value greater than 1, multiple
.I rtrace
processes will be used to accelerate computation on a shared
memory machine.
Note that there is no benefit to using more processes
than there are local CPUs available to do the work, and the
.I rtcontrib
process itself may use a considerable amount of CPU time.
.PP
Options may be given on the command line and/or read from the
environment and/or read from a file.
A command argument beginning with a dollar sign ('$') is immediately
replaced by the contents of the given environment variable.
A command argument beginning with an at sign ('@') is immediately
replaced by the contents of the given file.
.SH EXAMPLES
To compute the proportional contributions from sources modified
by "light1" vs. "light2" on a set of illuminance values:
.IP "" .2i
rtcontrib -I+ @render.opt -o c_%s.dat -m light1 -m light2 scene.oct < test.dat
.PP
To generate a pair of images corresponding to these two lights'
contributions:
.IP "" .2i
vwrays -ff -x 1024 -y 1024 -vf best.vf |
rtcontrib -ffc `vwrays -d -x 1024 -y 1024 -vf best.vf`
@render.opt -o c_%s.pic -m light1 -m light2 scene.oct
.PP
These images may then be recombined using the desired outputs
of light1 and light2:
.IP "" .2i
pcomb -c 100 90 75 c_light1.pic -c 50 55 57 c_light2.pic > combined.pic
.PP
To compute an array of illuminance contributions according to a Tregenza sky:
.IP "" .2i
rtcontrib -b tbin -o sky.dat -m skyglow -b 0 -o ground.dat -m groundglow
@render.opt -f tregenza.cal scene.oct < test.dat
.SH ENVIRONMENT
RAYPATH		path to search for -f files
.SH AUTHOR
Greg Ward
.SH "SEE ALSO"
cnt(1), getinfo(1), pcomb(1), pfilt(1), ra_rgbe(1),
rcalc(1), rpict(1), rtrace(1), vwrays(1), ximage(1)
