.\" RCSid "$Id: thf2rad.1,v 1.2 2003/12/09 15:59:07 greg Exp $"
.TH THF2RAD 1 11/15/93 RADIANCE
.SH NAME
thf2rad - convert GDS things file to RADIANCE description
.SH SYNOPSIS
.B thf2rad
[
.B "\-n name"
][
.B "\-r rad"
]
[
.B input ..
]
.SH DESCRIPTION
.I Thf2rad
converts one or more GDS things files to a RADIANCE scene description.
The material names for the surfaces will be those assigned in GDS.
The
.I \-n
option may be used to give a name prefix to all the surfaces.
The
.I \-r
option may be used to specify a radius for line segments.
By default, this value is zero, which means that lines will be ignored.
By setting it to some positive value, cylinders of the given radius
will represent lines.
.SH EXAMPLE
To translate two things files into one RADIANCE file with the prefix "gds":
.IP "" .2i
thf2rad -n gds building1.thf building2.thf > building1+2.rad
.PP
To create an octree directly from a things file, giving lines a radius
of .1:
.IP "" .2i
oconv source.rad materials.rad '\\!thf2rad -r .1 building1.thf' > building1.oct
.SH AUTHOR
Greg Ward and Charles Ehrlich
.SH "SEE ALSO"
arch2rad(1), ies2rad(1), oconv(1), xform(1)
